---
webservers:
  hosts:
    web-server-1:
      ansible_host: 10.1.11.196

    web-server-2:
      ansible_host: 10.1.11.192

databases:
  hosts:
    database:
      ansible_host: 10.1.11.56

load_balancers:
  hosts:
    load-balancer:
      ansible_host: 10.1.1.8