---
webservers:
  hosts:
    web-server-1:
      ansible_host: 10.1.11.173

    web-server-2:
      ansible_host: 10.1.11.9

databases:
  hosts:
    database:
      ansible_host: 10.1.11.50

load_balancers:
  hosts:
    load-balancer:
      ansible_host: 10.1.1.235
