---
ungrouped:
  hosts:
    consul_server:
      ansible_host: 10.5.11.51
consul_agents:
  children:
    webservers:
      hosts:
        web-server-1:
          ansible_host: 10.3.11.97
        web-server-2:
          ansible_host: 10.3.11.59
    databases:
      hosts:
        database-1:
          ansible_host: 10.3.11.204
    load_balancers:
      hosts:
        load-balancer-1:
          ansible_host: 10.3.1.149
