- name: Test
  hosts: jenkins
  become: true

  tasks:
    - name: ping
      ansible.builtin.ping: null

    - name: Install java
      ansible.builtin.apt:
        name: openjdk-21-jre
        state: present
        update_cache: yes

    - name: Add jenkins apt repository key.
      shell: |
         wget -O /etc/apt/keyrings/jenkins-keyring.asc https://pkg.jenkins.io/debian-stable/jenkins.io-2026.key
         echo "deb [signed-by=/etc/apt/keyrings/jenkins-keyring.asc]" https://pkg.jenkins.io/debian-stable binary/ | sudo tee /etc/apt/sources.list.d/jenkins.list > /dev/null

    - name: Install jenkins
      ansible.builtin.apt:
        name: jenkins
        state: present
        update_cache: yes
    
    - name: Creates directory for desabling initial page
      ansible.builtin.file:
        path: /var/lib/jenkins/init.groovy.d/
        state: directory

    - name: Copy file with owner and permissions
      ansible.builtin.copy:
        src: ./templates/disable_unlock.groovy
        dest: /var/lib/jenkins/init.groovy.d/

    - name: Copy file with owner and permissions
      ansible.builtin.copy:
        src: ./templates/create_user.groovy
        dest: /var/lib/jenkins/init.groovy.d/

    - name: install plugin
      jenkins_plugin:
        name: "{{ item }}"
        state: latest
        url_username: admin
        url_password: admin
      with_items: "{{ jenkins_plugins }}"

    - name: Restart jenkins service
      service:
        name: jenkins
        state: restarted  
