- name: Try to ping
  hosts: database
  gather_facts: true
  vars_files:
    - ./group_vars/database.yml
  tasks:
    - name: Update and upgrade apt packages
      become: true
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400 

    - name: Installing Mysql  and dependencies
      package:
       name: "{{item}}"
       state: present
       update_cache: yes
      loop:
       - mysql-server
       - python3-mysqldb
      become: true

    - name: start and enable mysql service
      service:
        name: mysql
        state: started
        enabled: yes

    - name: Create the database
      ansible.mysql.mysql_db:
        name: "{{ db_name }}"
        state: present
        login_unix_socket: /var/run/mysqld/mysqld.sock

    - name: Create the database user
      ansible.mysql.mysql_user:
        name: "{{ db_user }}"
        password: "{{ db_password }}"
        host: "%"
        priv: "*.*:ALL"
        state: present
        login_unix_socket: /var/run/mysqld/mysqld.sock
      
    - name: Clone the config files 
      ansible.builtin.git:
        repo: "https://github.com/SkeletonCrew1/SkelBirdView.git"
        dest: /home/configs
        version: config_files

    - name: Move MySQL config file
      ansible.builtin.copy:
        src: /home/configs/database_config/mysqld.cnf
        dest: /etc/mysql/mysql.conf.d/mysqld.cnf
        remote_src: yes

    - name: Restart MySQL service
      ansible.builtin.systemd_service:
        name: mysql
        state: restarted
        enabled: true
      become: true

    - name: ensure mysql is running
      service:
        name: mysql
        state: started
