---
public_keys:
  - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHClFx+zuYSEUh/SO6Pk8ofZGM5wzwax37azfclSyniY" # Maksym Semehen
  - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOHohMxMgTps1D8g94vQUjAKP0yvFTkuDT47hdEUf5ni" # Oleh Konovaliuk
  - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPR8PEc6WSE7DHWNf8d+2nxYMnAbNQGAzgRFodVCtBs8" # Vitalii Oliinyk
  - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHXE4vbal0u9BvRq/MpXEUM5qXZx0BrfTAN1extk6+Ff" # Roman Missuryn
  - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMI+78+qHyE5qxg9G2J3n4ZkCoNY6D0ArptLs3ZFAAYE" # Denis Folyush
