---
- name: Configure golden image
  hosts: all
  become: true

  vars_files:
    - vars/public_keys.yml

  tasks:
    - name: Configure timezone
      community.general.timezone:
        name: Europe/Kyiv

    - name: Add authorized SSH keys
      authorized_key:
        user: vagrant
        state: present
        key: "{{ item }}"
      loop: "{{ public_keys }}"

    - name: Add Trivy repository
      shell: |
        wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | gpg --dearmor | sudo tee /usr/share/keyrings/trivy.gpg > /dev/null
        echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb generic main" | sudo tee /etc/apt/sources.list.d/trivy.list > /dev/null

    - name: Install packages
      apt:
        name:
          - git
          - trivy
        state: present
        update_cache: true

    - name: Create Trivy log directory
      file:
        path: /var/log/trivy
        state: directory
        owner: root
        group: root
        mode: "0755"

    - name: Schedule Trivy filesystem scan
      cron:
        name: "Trivy filesystem scan"
        minute: "0"
        hour: "2"
        user: root
        job: 'trivy fs --scanners vuln,secret --severity HIGH,CRITICAL --skip-dirs /proc,/sys,/dev,/run,/boot,/tmp,/var/tmp,/vagrant --skip-dirs "**/venv,**/.venv,**/env,**/.env" --timeout 15m --format table --output "/var/log/trivy/security-summary-$(hostname)-$(date +\%Y-\%m-\%d-\%H-\%M).txt" /'
