---
- name: Configure golden image
  hosts: all

  vars_files:
    - vars/public_keys.yml

  tasks:
    - name: Configure timezone
      community.general.timezone:
        name: Europe/Kyiv

    - name: Add authorized SSH keys
      authorized_key:
        user: vagrant
        state: present
        key: "{{ item }}"
      loop: "{{ public_keys }}"

    - name: Add Trivy repository
      shell: |
        wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | gpg --dearmor | sudo tee /usr/share/keyrings/trivy.gpg
        echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb generic main" | sudo tee /etc/apt/sources.list.d/trivy.list

    - name: Install packages
      apt:
        name:
          - git
          - trivy
        state: present
        update_cache: true
