---
- name: Configure database
  hosts: databases
  become: true
  tasks:
    - name: Look Up Secrets
      ansible.builtin.set_fact:
        JSON_DB_USER: "{{ lookup('env', 'DB_USER') }}"
        JSON_DB_NAME: "{{ lookup('env', 'DB_NAME') }}"
        JSON_DB_PASSWORD: "{{ lookup('env', 'DB_PASSWORD') }}"
        cacheable: true
    - name: Lookup secretsmanager secret in the current region
      ansible.builtin.debug: msg="{{ lookup('amazon.aws.aws_secret', 'BIRDWATCHING_DB_NAME', bypath=true,region='eu-north-1') }}"
    - name: Parse the database variables
      ansible.builtin.set_fact:
        DB_USER: "{{ JSON_DB_USER | ansible.builtin.from_json | community.general.json_query('DB_USER') }}"
        DB_NAME: "{{ JSON_DB_NAME | ansible.builtin.from_json | community.general.json_query('DB_NAME') }}"
        DB_PASSWORD: "{{ JSON_DB_PASSWORD | ansible.builtin.from_json | community.general.json_query('DB_PASSWORD') }}"
    - name: Print version
      debug:
        msg: "Ansible Version: {{ DB_NAME }}"
    - name: Installing Mysql and dependencies
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      loop:
        - mysql-server
        - python3-pymysql

    - name: start and enable mysql service
      ansible.builtin.service:
        name: mysql
        state: started
        enabled: yes

    - name: Clone the config files
      ansible.builtin.git:
        repo: "https://github.com/SkeletonCrew1/SkelBirdView.git"
        dest: /home/configs
        version: config_files

    - name: Move MySQL config file
      ansible.builtin.copy:
        src: /home/configs/database_config/mysqld.cnf
        dest: /etc/mysql/mysql.conf.d/mysqld.cnf
        remote_src: yes

    - name: Restart MySQL service
      ansible.builtin.systemd_service:
        name: mysql
        state: restarted
        enabled: true

    - name: ensure mysql is running
      ansible.builtin.service:
        name: mysql
        state: started

    - name: Create the database user
      community.mysql.mysql_user:
        name: "{{ DB_USER }}"
        plugin_auth_string: "{{ DB_PASSWORD }}"
        host: "%"
        priv: "*.*:ALL"
        state: present
        plugin: caching_sha2_password
        login_unix_socket: /var/run/mysqld/mysqld.sock

    - name: Create the database
      community.mysql.mysql_db:
        name: "{{ DB_NAME }}"
        state: present
        login_user: "{{ DB_USER }}"
        login_password: "{{ DB_PASSWORD }}"
        login_unix_socket: /var/run/mysqld/mysqld.sock

    - name: Restart Datadog Agent
      ansible.builtin.systemd_service:
        name: datadog-agent
        state: restarted
        enabled: true
