---
- name: Configure golden image
  hosts: all
  become: true

  vars_files:
    - vars/users.yml

  tasks:
    - name: Configure timezone
      community.general.timezone:
        name: Europe/Kyiv

    - name: Create user for each team member
      ansible.builtin.user:
        name: "{{ item.name }}"
        shell: /bin/bash
        groups: sudo
        append: true
        state: present
      loop: "{{ users }}"

    - name: Add authorized SSH key for each user
      ansible.posix.authorized_key:
        user: "{{ item.name }}"
        state: present
        key: "{{ item.ssh_key }}"
      loop: "{{ users }}"

    - name: Allow passwordless sudo for each user
      ansible.builtin.copy:
        dest: /etc/sudoers.d/team
        owner: root
        group: root
        mode: "0440"
        validate: "visudo -cf %s"
        content: "%sudo ALL=(ALL:ALL) NOPASSWD: ALL\n"

    - name: Add Trivy repository
      ansible.builtin.deb822_repository:
        name: trivy
        uris: https://aquasecurity.github.io/trivy-repo/deb
        suites: generic
        components: "main"
        signed_by: https://aquasecurity.github.io/trivy-repo/deb/public.key
        state: present

    - name: Add Datadog repository
      ansible.builtin.deb822_repository:
        name: datadog
        uris: https://apt.datadoghq.com/
        suites: stable
        components: "7"
        signed_by: https://keys.datadoghq.com/DATADOG_APT_KEY_CURRENT.public
        state: present

    - name: Install packages
      ansible.builtin.apt:
        name:
          - trivy
          - datadog-agent
        state: present
        update_cache: true

    - name: Create Trivy log directory
      ansible.builtin.file:
        path: /var/log/trivy
        state: directory
        owner: root
        group: root
        mode: "0755"

    - name: Schedule Trivy filesystem scan
      ansible.builtin.cron:
        name: "Trivy filesystem scan"
        minute: "0"
        hour: "2"
        user: root
        job: >
          trivy fs
          --scanners vuln,secret
          --severity HIGH,CRITICAL
          --skip-dirs /proc,/sys,/dev,/run,/boot,/tmp,/var/tmp,/vagrant
          --skip-dirs "**/venv,**/.venv,**/env,**/.env"
          --timeout 15m
          --format table
          --output "/var/log/trivy/security-summary-$(hostname)-$(date +\%Y-\%m-\%d-\%H-\%M).txt"
          /

    - name: Datadog Base Config
      ansible.builtin.copy:
        dest: /etc/datadog-agent/datadog.yaml
        content: |
          secret_backend_type: aws.secrets
          secret_backend_config:
            aws_session:
              aws_region: us-east-1

          api_key: ENC[DatadogAgent/Production;api_key]
          site: "datadoghq.eu"

          process_config:
            process_collection:
              enabled: true

          logs_enabled: true

    - name: Restart Datadog Agent
      ansible.builtin.systemd_service:
        name: datadog-agent
        state: restarted
        enabled: true
