- name: Set up load-balancer
  hosts: load_balancers
  become: true

  tasks:
    - name: Look Up Secrets
      ansible.builtin.set_fact:
        JSON_SERVER1: "{{ lookup('env', 'SERVER1')  }}"
        JSON_SERVER2: "{{ lookup('env', 'SERVER2')  }}"
        cacheable: true

    - name : Parse the load balancer variables
      ansible.builtin.set_fact:
        # SERVER1: "{{ JSON_SERVER1 | ansible.builtin.from_json | community.general.json_query('SERVER1') }}"
        # SERVER2: "{{ JSON_SERVER2 | ansible.builtin.from_json | community.general.json_query('SERVER2') }}"
        

    - name: Install dependencies and update apt
      ansible.builtin.apt:
        name: "nginx"
        state: present
        update_cache: true

    - name: Render template for Nginx
      ansible.builtin.template:
        src: load_balancer.j2
        dest: /etc/nginx/sites-available/default
        mode: '0755'
      vars:
        SERVER1: "{{ SERVER1 }}"
        SERVER2: "{{ SERVER2 }}"

    - name: Restarn Nginx load balancer
      ansible.builtin.systemd_service:
        name: nginx
        state: restarted
        enabled: true

    - name: Make sure 'nginx' is started
      systemd:
        name: nginx
        state: started
        enabled: yes

    - name: Restart Datadog Agent
      ansible.builtin.systemd_service:
        name: datadog-agent
        state: restarted
        enabled: true
