- name: Set up load-balancer
  hosts: load_balancers
  become: true

  tasks:
    - name: Look Up Secrets
      ansible.builtin.set_fact:
        SERVER1: "{{ lookup('env', 'SERVER1')  }}"
        SERVER2: "{{ lookup('env', 'SERVER2')  }}"
        CERTBOT_CERT: "{{ lookup('env', 'BIRDWATCHING_CERTBOT_CERT') }}"
        CERTBOT_KEY: "{{ lookup('env', 'BIRDWATCHING_CERTBOT_KEY') }}"
        cacheable: true

    - name: Install dependencies and update apt
      ansible.builtin.apt:
        name: "nginx"
        state: present
        update_cache: true

    - name: Render template for Nginx
      ansible.builtin.template:
        src: load_balancer.j2
        dest: /etc/nginx/sites-available/default
        mode: '0755'
      vars:
        SERVER1: "{{ SERVER1 }}"
        SERVER2: "{{ SERVER2 }}"

    - name: Ensure target SSL directory exists
      ansible.builtin.file:
        path: /etc/letsencrypt/live/birdview.pp.ua
        state: directory
        recurse: true
        owner: root
        group: root
        mode: '0755'

    - name: Write SSL fullchain certificate
      ansible.builtin.copy:
        content: "{{ CERTBOT_CERT }}"
        dest: /etc/letsencrypt/live/birdview.pp.ua/fullchain.pem
        owner: root
        group: root
        mode: '0644'

    - name: Write SSL private key
      ansible.builtin.copy:
        content: "{{ CERTBOT_KEY }}"
        dest: /etc/letsencrypt/live/birdview.pp.ua/privkey.pem
        owner: root
        group: root
        mode: '0600'
      no_log: true

    - name: Make sure 'nginx' is started
      systemd:
        name: nginx
        state: started
        enabled: yes

    - name: Restart Datadog Agent
      ansible.builtin.systemd_service:
        name: datadog-agent
        state: restarted
        enabled: true
