---
- name: Try to ping
  hosts: webservers
  gather_facts: true
  vars:
    packages:
      - python3
      - python3-pip
      - python3-venv
  tasks:
    - name: Setting host facts using complex arguments
      ansible.builtin.set_fact:
        DB_USER: "{{ lookup('env', 'DB_USER') }}"
        DB_NAME: "{{ lookup('env', 'DB_NAME') }}"
        DB_PASSWORD: "{{ lookup('env', 'DB_PASSWORD') }}"
        DB_HOST: "{{ lookup('env', 'DB_HOST') }}"
        AWS_ACCESS_KEY: "{{ lookup('env', 'AWS_ACCESS_KEY') }}"
        AWS_SECRET_KEY: "{{ lookup('env', 'AWS_SECRET_KEY') }}"
        S3_BUCKET: "{{ lookup('env', 'S3_BUCKET') }}"
        cacheable: true

    - name: Install dependencies and update apt
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop: "{{ packages }}"
      become: true

    - name: Copy source code
      ansible.builtin.git:
        repo: "https://github.com/SkeletonCrew1/SkelBirdView.git"
        dest: /home/vagrant/application
        force: yes
      become: true

    - name: Template .env
      ansible.builtin.template:
        src:  ./templates/env_templates
        dest: /home/vagrant/application/web-servers/.env
      vars:
        DB_USER: "{{ DB_USER }}"
        DB_NAME: "{{ DB_NAME }}"
        DB_PASSWORD: "{{ DB_PASSWORD }}"
        DB_HOST: "{{ DB_HOST }}"
        AWS_ACCESS_KEY: "{{ AWS_ACCESS_KEY }}"
        AWS_SECRET_KEY: "{{ AWS_SECRET_KEY }}"
        S3_BUCKET: "{{ S3_BUCKET }}"
      become: true

    - name: Manually create the initial virtualenv
      command:
        cmd: python3 -m venv {{ venv_path }}
        creates: "/user/home/venvs/myenv"
      vars:
        venv_path: "/home/vagrant/application/web-servers/venv" 
      become: true
      
    - name: Install requirements
      pip: 
        requirements: "/home/vagrant/application/web-servers/requirements.txt"
        virtualenv: "{{ venv_path }}"
      vars:
        venv_path: "/home/vagrant/application/web-servers/venv"

    - name: Change file ownership, group and permissions app.py
      ansible.builtin.file:
        path: /home/vagrant/application/web-servers/app.py
        owner: vagrant
        group: vagrant
        mode: '0755'

    - name: Change file ownership, group and permissions .env
      ansible.builtin.file:
        path: /home/vagrant/application/web-servers/.env
        owner: vagrant
        group: vagrant
        mode: '0755'

    - name: Move service file for the app  
      ansible.builtin.copy:
        src: /home/configs/web_server_config/SkelBirdView.service
        dest: /etc/systemd/system/SkelBirdView.service
        owner: vagrant
        group: vagrant
        mode: '0644'
        remote_src: yes

    - name: Change permissions for web-servers folder
      ansible.builtin.file:
        dest: "/home/vagrant/application/web-servers/"
        owner: 'vagrant'
        group: 'vagrant'
        recurse: true 
        mode: u=rwX,g=rX,o=rX

    - name: Make sure  service that starts app.py is started and enabled
      systemd:
        name: SkelBirdView.service
        state: started
        enabled: yes
        daemon_reload: yes