---
name: Linter

on:
  pull_request:
  workflow_dispatch:
  push:

jobs:
  changes:
    permissions: write-all
    runs-on: ubuntu-latest
    outputs:
      actions: ${{ steps.filter.outputs.actions }}
      python: ${{ steps.filter.outputs.python }}
    steps:
      - uses: actions/checkout@v5
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            actions:
              - ".github/workflows/**"
            python:
              - "web-servers/**"


  actions-lint:
    needs: changes
    if: needs.changes.outputs.actions == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Run yaml linter against action workflows
        run: |
          sudo apt update
          sudo apt install yamllint -y
          yamllint ./.github/workflows/**
# Just a placeholder for when we start using yaml


  python-lint:
    needs: changes
    if: needs.changes.outputs.python == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Run flake8 against Python applications
        run: |
          python -m pip install --upgrade pip
          python -m pip install flake8
          flake8 --max-line-length 180 web-servers/**