name: Terraform PR Check

on:
  workflow_dispatch:
  pull_request:

jobs:
  run-terraform-plan:
    strategy:
      matrix:
        tffolders: [terraform/application,
                    terraform/jenkins-consul,
                    terraform/roles,
                    terraform/s3-for-application,
                    terraform/s3-for-state,
                    terraform/tmp-users,
                    terraform/vpc]
    runs-on: ubuntu-latest

    env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup terraform
        uses: hashicorp/setup-terraform@v4
        with:
            terraform_version: "1.15"

      - name: Run tf init
        working-directory: ${{ matrix.tffolders }}
        run: terraform init

      - name: Run tf validate
        working-directory: ${{ matrix.tffolders }}
        run: terraform validate
