name: Terraform PR Check

on:
  workflow_dispatch:
  pull_request:

jobs:
  run-terraform-plan:
    strategy:
      matrix:
        tffolders: [terraform/application,
                    terraform/jenkins-consul]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup terraform
        uses: hashicorp/setup-terraform@v4
        with:
            terraform_version: "1.15"

      - name: Run python script with gihub secrets
        working-directory: ${{ matrix.tffolders }}
        run: terraform init

      - name: Run python script with gihub secrets
        working-directory: ${{ matrix.tffolders }}
        run: terraform plan
